spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/laborsystem
    username: root
    password: lilekang
mybatis:
  config-location: classpath:mybatis/mybatis.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
#  type-aliases-package:com.llk.laborsystem.bean
  #redis集群
redis:
  host: 127.0.0.1
  port: 6379
  timeout: 20000
  #    集群环境打开下面注释，单机不需要打开
  #    cluster:
  #      集群信息
  #      nodes: xxx.xxx.xxx.xxx:xxxx,xxx.xxx.xxx.xxx:xxxx,xxx.xxx.xxx.xxx:xxxx
  #      #默认值是5 一般当此值设置过大时，容易报：Too many Cluster redirections
  #      maxRedirects: 3
  pool:
    max-active: 8
    min-idle: 0
    max-idle: 8
    max-wait: -1
  password:
application:
  name: spring-boot-redis
